### ISSUE TITLE
Create a 'Give a Talk' page.

### ISSUE THREAD

**Issue by briandailey** [pynashorg/pynashorg.github.com#62]
Embed a Google form where we can collect information from folks who are interested in giving talks at PyNash lecture night. Gather:
- Name
- Email
- Audience level (Beginner, intermediate, advanced)
- Subject
- Abstract
- Dates Available

**Comment by epochblue** [comment]
It's not embedded (though that's something we can change), but the new redesign (#70) has a link to our speaker submission form. Closing this for now.
